name: hpcc4j Nightly Test Suite

on: workflow_dispatch

jobs:
  test-against-platform:
    runs-on: ubuntu-latest

    services:
      hpccsystems-platform:
        image: hpccsystems/platform
        options: >-
          --health-cmd "/etc/init.d/hpcc-init start"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 3
        ports:
          - 8510:8510
          - 8010:8010

    steps:
      
    - uses: actions/checkout@v2

    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.2
    
    # speed things up with caching from https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven
    - name: Cashe Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
  
    - name: Build with Maven
      run: mvn -B --activate-profiles jenkins-on-demand -Dmaven.gpg.skip=true -Dmaven.test.failure.ignore=true install
